"""empty message

Revision ID: cc9dfb0deebe
Revises: 6ad1b7758c76
Create Date: 2024-05-03 14:35:56.040568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc9dfb0deebe'
down_revision: Union[str, None] = '6ad1b7758c76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('task_msg', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'task_msg')
    # ### end Alembic commands ###
